spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/songs_manager
    username: admin
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
